package:
    name: roku_app
    version: "0.0.2.2"

#build:
    #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    git_url: ../

requirements:
  build:
    - python
    - numpy
    - libpython # [py2k and win]
    - pandas
    - matplotlib
    - requests

  run:
    - python
    - numpy
    - python-dateutil
    - pytz
    - pandas
    - matplotlib
    - requests

test:
  imports:
    - roku_app

  requires:
    - nose

  commands:
    - nosetests roku_app

#about
  #home: http://pandas.pydata.org
  #license: BSD
